#include "stdafx.h"
#include "DragonAnimationString.h"

DRAGON_ANIM_LINK(DRAGON_ATTACK1);
DRAGON_ANIM_LINK(DRAGON_ATTACK2);
DRAGON_ANIM_LINK(DRAGON_DEATH);
DRAGON_ANIM_LINK(DRAGON_EAT);
DRAGON_ANIM_LINK(DRAGON_FLY);
DRAGON_ANIM_LINK(DRAGON_FLY_ATTACK);
DRAGON_ANIM_LINK(DRAGON_FLY_BREATH);
DRAGON_ANIM_LINK(DRAGON_FLY_DEATH);
DRAGON_ANIM_LINK(DRAGON_FLY_FAST);
DRAGON_ANIM_LINK(DRAGON_FLY_HIT);
DRAGON_ANIM_LINK(DRAGON_HIT1);
DRAGON_ANIM_LINK(DRAGON_HIT2);
DRAGON_ANIM_LINK(DRAGON_IDLE);
DRAGON_ANIM_LINK(DRAGON_RUN);
DRAGON_ANIM_LINK(DRAGON_WALK);
DRAGON_ANIM_LINK(DRAGON_STAND);
DRAGON_ANIM_LINK(DRAGON_WHIP_TAIL);

void InitDragonAnimation()
{
	DRAGON_ANIM_DEFINE(DRAGON_ATTACK1,false,false,false,1.0f,0.2f,0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_ATTACK2, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_DEATH, true, true, true, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_EAT, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_FLY, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_FLY_ATTACK, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_FLY_BREATH, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_FLY_DEATH, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_FLY_FAST, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_FLY_HIT, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_HIT1, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_HIT2, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_IDLE, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_RUN, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_WALK, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_STAND, false, false, false, 1.0f, 0.2f, 0.2f);
	DRAGON_ANIM_DEFINE(DRAGON_WHIP_TAIL, false, false, false, 1.0f, 0.2f, 0.2f);
}
