#include "stdafx.h"
#include "LizardAnimationString.h"

LIZARD_ANIM_LINK(LIZARD_ATTACK)
LIZARD_ANIM_LINK(LIZARD_BITE)
LIZARD_ANIM_LINK(LIZARD_DEATH)
LIZARD_ANIM_LINK(LIZARD_HIT1)
LIZARD_ANIM_LINK(LIZARD_HIT2)
LIZARD_ANIM_LINK(LIZARD_IDLE)
LIZARD_ANIM_LINK(LIZARD_ROAR)
LIZARD_ANIM_LINK(LIZARD_RUN)
LIZARD_ANIM_LINK(LIZARD_SPIT)
LIZARD_ANIM_LINK(LIZARD_STAND)
LIZARD_ANIM_LINK(LIZARD_WALK)
void InitLizardAnimation()
{
	LIZARD_ANIM_DEFINE(LIZARD_ATTACK, false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_BITE, false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_DEATH, true, true, true, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_HIT1, false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_HIT2, false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_IDLE,false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_ROAR,false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_RUN,false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_SPIT,false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_STAND,false, false, false, 1.0f, 0.2f, 0.2f);
	LIZARD_ANIM_DEFINE(LIZARD_WALK,false, false, false, 1.0f, 0.2f, 0.2f);
}
