#ifndef PLAYER_ANIMATION_STRING_H
#define PLAYER_ANIMATION_STRING_H

enum PlayerAnimationEnum
{
	eWarRetreat = 0,
	eWalkingBack,
	eClimbingLadder,
	eCrouching,
	eDrinking,
	eEating,
	eExplanation,
	eJumpRunning,
	eRun,
	eSayNo,
	eSneaking,
	eStandingFree,
	eSwimming,
	eTalking,
	eWarThrowingAxe,
	eWarThrowingSpear,
	eWarCombatMode,
	eWarDying,
	eWarBackwards,
	eWarBelowHighSwing,
	eWarCharging,
	eWarDodgeToLeft,
	eWarDodgeToRight,
	eWarMovingLeft,
	eWarMovingRight,
	eWarParryFromStraightDown,
	eWarParryFront,
	eWarRunSwingLeft,
	eWarRunSwingRight,
	eWarRunSwingUpDown,
	eWarShieldBlock,
	eWarShieldBlow,
	eWarSpecialAttackA,
	eWarSpecialAttackB,
	eWarSwingHighStraigtDown,
	eWarSwingLeft,
	eWarSwingRight,
	eWarTakingHit,
	eWarThrustMid,
	eBoring,
	eCameUp,
	eLookingAround,
	eMakingItem,
	ePickObject,
	eSalute,
	eSitDown,
	eSitting,
	eHeroWalk
};

static const char *PlayerAnimationString[] = 
{
	{"Hero_War_retreat"},
	{ "Hero_walking_back"},
	{ "hero_Climbing_ladder"},
	{ "hero_Crouching"},
	{ "hero_Drinking"},
	{ "hero_Eating"},
	{ "hero_Explanation"},
	{ "hero_Jump_running"},
	{ "hero_Run"},
	{"hero_Say_No"},
	{"hero_Sneaking"},
	{"hero_Standing_Free"},
	{"hero_Swimming"},
	{"hero_Talking"},
	{"hero_ThrowingAxe_throwing"},
	{"hero_ThrowingSpear_throwing"},
	{"hero_War_COMBAT_MODE"},
	{"hero_War_Dying"},
	{"hero_War_backwards"},
	{"hero_War_below_high_swing"},
	{"hero_War_charging"},
	{"hero_War_dodge_to_left"},
	{"hero_War_dodge_to_right"},
	{"hero_War_moving_left"},
	{"hero_War_moving_right"},
	{"hero_War_parry_from_stright_dow"},
	{"hero_War_parry_front"},
	{"hero_War_run_swing_left"},
	{"hero_War_run_swing_right"},
	{"hero_War_run_swing_up_down"},
	{"hero_War_shield_block"},
	{"hero_War_shield_blow"},
	{"hero_War_special_attack_A"},
	{"hero_War_special_attack_B"},
	{"hero_war_swing_high_straight_do"},
	{"hero_War_swing_left"},
	{"hero_War_swing_right"},
	{"hero_War_taking_hit"},
	{"hero_War_thrust_mid"},
	{"hero_boring"},
	{"hero_came_up"},
	{"hero_looking_around"},
	{"hero_making_item"},
	{"hero_pick_object"},
	{"hero_salute"},
	{"hero_sit_down"},
	{"hero_sitting"},
	{"hero_walk"}
};

#endif
