#include "stdafx.h"
#include "TurtleAnimationString.h"


TURTLE_ANIM_LINK(TURTLE_BITE1);
TURTLE_ANIM_LINK(TURTLE_BITE2);
TURTLE_ANIM_LINK(TURTLE_BREATHFIRE);
TURTLE_ANIM_LINK(TURTLE_DEATH);
TURTLE_ANIM_LINK(TURTLE_EARTHQUAKE);
TURTLE_ANIM_LINK(TURTLE_HIT1);
TURTLE_ANIM_LINK(TURTLE_HIT2);
TURTLE_ANIM_LINK(TURTLE_ROAR);
TURTLE_ANIM_LINK(TURTLE_SPIT);
TURTLE_ANIM_LINK(TURTLE_STAND);
TURTLE_ANIM_LINK(TURTLE_WALK);
void InitTurtleAnimation()
{
	TURTLE_ANIM_DEFINE(TURTLE_BITE1, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_BITE2, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_BREATHFIRE, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_DEATH, true, true, true, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_EARTHQUAKE, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_HIT1, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_HIT2, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_ROAR, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_SPIT, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_STAND, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_WALK, false, false, false, 1.0f, 0.2f, 0.2f);
}
