#include "stdafx.h"
#include "TurtleAnimationString.h"



TURTLE_ANIM_LINK(TURTLE_ATTACK1);
TURTLE_ANIM_LINK(TURTLE_ATTACK2);
TURTLE_ANIM_LINK(TURTLE_ATTACK3);
TURTLE_ANIM_LINK(TURTLE_DEATH);
TURTLE_ANIM_LINK(TURTLE_HIT1);
TURTLE_ANIM_LINK(TURTLE_HIT2);
TURTLE_ANIM_LINK(TURTLE_IDLE);
TURTLE_ANIM_LINK(TURTLE_MOVE);
TURTLE_ANIM_LINK(TURTLE_ROAR);
TURTLE_ANIM_LINK(TURTLE_STAND);

void InitTurtleAnimation()
{
	TURTLE_ANIM_DEFINE(TURTLE_ATTACK1, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_ATTACK2, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_ATTACK3, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_DEATH, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_HIT1, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_HIT2, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_IDLE, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_MOVE, false, false, false, 1.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_ROAR, false, true, false, 2.0f, 0.2f, 0.2f);
	TURTLE_ANIM_DEFINE(TURTLE_STAND, false, false, false, 1.0f, 0.2f, 0.2f);
}
